modLoader = "javafml"
loaderVersion = "[38,)"
issueTrackerURL = "https://github.com/Reoseah/catwalks-incorporated/issues"
license = "MIT"

[[mods]]
modId = "catwalksinc"
version = "${version}"
displayName = "Catwalks Inc."
authors = "Reoseah"
description = '''
Catwalks, caged ladders and other industrial stuff for building or just decoration.
'''
#logoFile = ""

[[dependencies.catwalksinc]]
modId = "forge"
mandatory = true
versionRange = "[38,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.catwalksinc]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.catwalksinc]]
modId = "architectury"
mandatory = true
versionRange = "[3.2.47,)"
ordering = "AFTER"
side = "BOTH"